on: [push, pull_request, workflow_dispatch]
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x, 1.25.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Run tests
      run: make test
